// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrontEndProgramacion2Final.Models;

public partial class ArticuloRelacionado
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdPrimerArticulo { get; set; }

    public int IdSegundoArticulo { get; set; }

    public virtual Articulo IdPrimerArticuloNavigation { get; set; }

    public virtual Articulo IdSegundoArticuloNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}