// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrontEndProgramacion2Final.Models;

public partial class Resena
{
    public int Id { get; set; }

    public int IdUsuario { get; set; }

    public int IdArticulo { get; set; }

    public int Calificacion { get; set; }

    public string Descripcion { get; set; }

    public virtual Articulo IdArticuloNavigation { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}