// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FrontEndProgramacion2Final.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Contrasena { get; set; }

    public string Email { get; set; }

    public string Rol { get; set; }

    public virtual ICollection<Articulo> Articulo { get; set; } = new List<Articulo>();

    public virtual ICollection<ArticuloRelacionado> ArticuloRelacionado { get; set; } = new List<ArticuloRelacionado>();

    public virtual ICollection<Resena> Resena { get; set; } = new List<Resena>();
}